apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: myapp
    type: database
spec:
  template:
    metadata:
      name: db-pod
      labels:
        app: myapp
        type: mysql-db
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"

  replicas: 1
  selector:
    matchLabels:
      app: myapp
      type: mysql-db
